### ISSUE TITLE
安全漏洞提醒

### ISSUE THREAD

**Issue by code6er** [zzcwill/projects#1]
漏洞类型：邮箱 SMTP 信息泄露

漏洞等级：高

漏洞地址：https://github.com/zzcwill/projects/blob/0290c1ef4bd90ef8a34767ca7af830093e4d2591/node-express-demo/controller/email.js

漏洞危害：任何人可以通过 SMTP 账号密码收发邮件，进而通过邮箱重置其他平台密码

解决方案：重置 SMTP 密码并检查邮箱是否有敏感信息泄露（请勿只修改代码，历史版本库依旧可见）

本次扫描结果由 [ 码小六 ] https://github.com/4x99/code6 提供（欢迎 star）

**Comment by zzcwill** [comment]
重置 SMTP 密码了，并随便写了个
